// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocialMediaBlog.DatabaseContext;

#nullable disable

namespace SocialMediaBlog.Migrations
{
    [DbContext(typeof(SocialMediaBlogDbCtx))]
    [Migration("20251209230948_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("SocialMediaBlog.Account.AccountEntity", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("account");
                });

            modelBuilder.Entity("SocialMediaBlog.Message.MessagesEntity", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PostedBy")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimePostedEpoch")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("PostedBy");

                    b.ToTable("message");
                });

            modelBuilder.Entity("SocialMediaBlog.Message.MessagesEntity", b =>
                {
                    b.HasOne("SocialMediaBlog.Account.AccountEntity", "Account")
                        .WithMany("MessageEntities")
                        .HasForeignKey("PostedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("SocialMediaBlog.Account.AccountEntity", b =>
                {
                    b.Navigation("MessageEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
